"""SummaryAgent — no-op stub retained for backwards-compatibility.

In the updated pipeline, summary generation is handled exclusively by
StudentTutorAgent (registered as the "learn_mode" node). SummaryAgent is
no longer wired into the graph but is kept here so any code that imports it
doesn't break.
"""
import logging
from typing import Any

from app.agents.base import BaseAgent

logger = logging.getLogger(__name__)


class SummaryAgent(BaseAgent):
    """
    Retained for API compatibility. The active implementation lives in
    StudentTutorAgent / app/agents/student_tutor_agent.py.
    """

    async def run(self, state: dict[str, Any]) -> dict[str, Any]:
        logger.info(
            "[summary_agent] Skipped — summaries generated by learn_mode node "
            "for lecture_id=%s",
            state.get("lecture_id", "unknown"),
        )
        return {"summaries_ready": True}
